version: '3.8'
services:
    web:
        env_file: ./app-service/.env
        build: ./app-service
        ports:
            - 3000:3000
        depends_on:
            - db
        volumes:
            - ./app-service/app:/code/app
    db:
        build: ./db-service
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3318:3306
        volumes: 
            - dbdata:/var/lib/mysql
volumes:
    dbdata: