version: '3.8'
services:
    app:
        build: ./app-service
        ports:
            - 3000:3000
        depends_on:
            - db
        environment:
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASS=${DB_PASS}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
        volumes:
            - ./app-service/app:/code/app
    db:
        build: ./db-service
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3318:3306
        volumes: 
            - dbdata:/var/lib/mysql
volumes:
    dbdata: